# Generated by Django 5.1.3 on 2024-12-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesense', '0022_alter_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edit_profile',
            field=models.BooleanField(default=False),
        ),
    ]
