# Generated by Django 5.1.3 on 2024-11-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_photo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_group',
            name='image',
            field=models.BinaryField(),
        ),
    ]
