# Generated by Django 5.1.3 on 2024-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_photo_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_group',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
