# Generated by Django 5.1.3 on 2024-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_photo_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_group',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
