# Generated by Django 5.1.3 on 2024-11-28 18:20

import django.db.models.deletion
import groups.model.group
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_photo_group_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_group',
            name='image2',
        ),
        migrations.CreateModel(
            name='PhotoGroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=groups.model.group.user_image_upload_path)),
                ('photo_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='groups.photo_group')),
            ],
        ),
    ]
