# Generated by Django 5.1.3 on 2024-12-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_customgroup_created_at_customgroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.customgroup'),
        ),
    ]
