# Generated by Django 5.1.3 on 2024-12-04 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_alter_subgroup_main_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('access', models.CharField(blank=True, choices=[('1', 'Private'), ('2', 'Public')], max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.customgroup')),
            ],
            options={
                'db_table': 'groups_sub_group',
            },
        ),
        migrations.DeleteModel(
            name='subgroup',
        ),
    ]
